### ISSUE TITLE
View Hex Grid

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#1]
## User Story
As a user, I want to view a grid playing field composed of hexagonal tiles. I want to view a variety of playing field layouts including a 6 tile-per-side hexagonal layout.

Story Points: 13
Priority: High
Risk: High

## Task Breakdown
- [x] Create and import hexagonal tile 3D model (1 hrs)
- [x] Create HexTile script that handles Unity game object properties and define Hex Tile Material Set (3 hrs)
- [x] Create HexTileController script that encapsulates tile coordinates and state (3 hrs)
- [x] Create Grid script and GridController that calculates HexTile coordinates and arranges grid layout (4 hrs)
- [x] Setup Unity scene with HexTile and Grid game objects.
- [x] Refactor scripts to implement interfaces for testability (3 hrs)
- [x] Write unit tests for HexTileController and GridController (4 hrs)
- [x] Unit testing second pass. (3 hrs)

- [x] Setup Logging Interface [Technical Feature]  (4hrs)
- [x] Setup Unit Tests Project  [Technical Feature]  (3hrs)
- [x] Setup .NET integration [Technical Feature] (6hrs)
