### ISSUE TITLE
Attack Ability

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#10]
## User Story
As a user, I want to have hero abilities that target and attack another character to deal damage to them.

Story Points: 8  
Priority: High
Risk: Medium

## Task Breakdown

- [x] Implement Ability as scriptable object for creating of many different type of Abilities from Unit editor (0.5 hr)
- [x] Give characters a set of Abilities (0.5 hrs)
- [x] Write AbilitySelectionController for handling user input while an ability is active and choose targets. (3hrs)
- [x] Write AbilityExecutionController for executing an ability (applying damage, updating UI). (1 hr)
- [x] Unit testing [5 hrs]
