### ISSUE TITLE
Pengwin - Ability 2 - Penguin Slide

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#100]
## User Story
As a user playing Pengwin, I would like to use my second ability.

Story Points: 5  
Priority: medium
Risk: low

Part of #72 

## Task Breakdown

- [x] Create Slide ability(0.5 hrs)
- [x] Implement straight line targeting [Technical Feature] (3 hrs)
- [x] UI, animation, and sound(1 hrs)
- [x] Unit tests(1 hrs)
