### ISSUE TITLE
Visual Feedback on Casting Ability

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#107]
## User Story
As a user, I would like to see the ability icon highlighted of the ability I am about to cast.

Story Points: 5
Priority: high  
Risk: medium

## Task Breakdown
- [x] Make ability image (image that looks like a button) in ability panel clickable and work like the shortcut (3 hrs)
- [x] Make ability images looks different when toggled and in enemy selection mode (3 hrs)
- [x] Create new events to handle those (1 hrs)
- [x] Tests (3 hrs)
