### ISSUE TITLE
Turn Based Combat

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#11]
## User Story
As a user, I want to game to proceed in sequential character turns ordered on the basis of character initiative.

Story Points: 5  
Priority: Medium 
Risk: High

## Task Breakdown

- [x] Implement a turn controller to constrain control flow to the character with the highest initiative (2.5 hrs)
- [x] Add logic to character controller to handle turn actions (1.5 hrs)
- [x] Add SelectionController handlers for when selected character is not active. (1 hr)
- [x] Update existing unit tests, write new unit tests for CharacterController turn actions SelectionController inactive character handlers. (2 hrs)
