### ISSUE TITLE
Agent Frog

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#112]
## User Story
As a user, I would like to have the Agent Frog character on my team.

Story Points: 8
Priority: high  
Risk: medium

## Task Breakdown
frog has low movement speed.
- [x] Ability 1 : Lick - autoattack, with range (2), goes in a straight line up until first obstacle (or character) hit, target loses 2 movement speed for 1 turn. (? hrs) 
- [x] Ability 2 : Hop - frog can hope to a tile up to 10 range. Frog can still use another ability after using this one.(? hrs)
- [x] Ability 3 : Tongue Pull - Same targeting concept as his Q, much higher range, pulls character towards him (can target allies, does not damage them)(cannot go over obstacles for now)(? hrs)
- [x] Ability 4 : Passive: Poison Aura - In a radius, enemies take damage (at the start of their turn) at the end of his turn.(? hrs)
