### ISSUE TITLE
Rocket Cat, Ability 4: Kamikaze

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#125]
## User Story

As a Rocket Cat player, I would like to use her ultimate ability to target enemies 

Story Points: 3
Priority: high 
Risk: medium

## Task Breakdown

- [x] Create Kamikaze ability(0.5 hrs)
- [x] UI, sound, and animations(1 hrs)
- [x] Create appropriate straight line and AOE selection [Technical Feature] (2 hrs)
- [x] Tests (1 hrs)
