### ISSUE TITLE
Store Account Data

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#13]
## User Story
As a user, I want a game account that will persist beyond a single playing session.

Story Points: 5 
Priority: High 
Risk: High

## Task Breakdown

- [x] Create a login UI with input fields for registering an account and logging into an account (3 hrs)
- [x] Connect login UI with local webserver (1 hr)
- [x] Basic routing for register, login, logout (3 hrs)
- [x] Encrypt password on client-side (0.5 hrs)
- [x] Set-up local MongoDB database, connect the server to the db, adapt routes to persist data in db (2.5hrs)
- [x] Write unit tests for reaching server routes (3 hrs)
