### ISSUE TITLE
Pengwin - Ability 4 - Arctic Fury

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#136]
## User Story
As a Pengwin Player, I would like to use Arctic Fury to duel the target enemy.

Story Points: 5 
Priority: high  
Risk: medium

## Task Breakdown

- [x] Handle deaths properly (3 hrs)
- [x] Make Animations Async (3 hrs)
- [x] Ensure all effects and basic attacks work correctly (4 hrs)
