### ISSUE TITLE
Consistent Behavior for Targeted Tiles

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#138]
## User Story
As a user, I want to be able to clearly tell which character is in range of being damaged or healed when an ability is selected.

Story Points: 8  
Priority: high  
Risk: medium

## Task Breakdown

- [x] Set Invalid Target to Show an X-overlay (4 hrs)
- [x] Set valid targets to strobe an appropriate colour (6 hrs)
- [x] Re-implement selection controllers to use new indicators (1 hr)
