### ISSUE TITLE
Matchmaking

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#14]
## User Story
As a user, when playing an online match I want to be matched with an other player.

Story Points: 5
Priority: ?  
Risk: High

## Task Breakdown

- [ ] Create UI that allows user to enter matchmaking (5 hrs)
- [ ] Reimplement Web Requests to use HttpClient rather than UnityWebRequest (5 hrs)
- [ ] Implement account level attribute to approximate player skill. (8 hrs)
- [ ] Implement match queue/search system for pairing players. (24 hrs)
  - [ ] TCP/IP from the client to be able to communicate to each client
- [ ] Unit testing. (10 hrs)
