### ISSUE TITLE
Allow Developers to See Submitted User Feedback

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#140]
## User Story
As a user, I would like to know that my sent feedback is accessible exclusively by people developing the application.

Story Points: 8
Priority: high
Risk: low

## Task Breakdown

- [x] Create the necessary components to make a secured new view (10 hrs)
- [x] Edit the routes to allow new feedback (1 hrs)
- [x] Add new unit tests for the new routes (1 hrs)
- [x] Add a new user to db with proper credentials and isAdmin (1hr) [Technical Feature]
