### ISSUE TITLE
Website Counter

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#141]
## User Story
As a user, I would like to know how many people downloaded the game's installer.

Story Points: 5 
Priority: medium  
Risk: medium

## Task Breakdown

- [x] Create Bitly Account (0.5 hrs)
- [x] Create the Click component (2 hrs)
- [x] Create the server router to hide bitly credentials (2 hrs)
- [x] Update functionality with new requests (2 hrs)
