### ISSUE TITLE
Hotkey for Ending Turn

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#142]
## User Story
As a user, I would like to alternatively end my turn with a keystroke, rather than using my mouse to click the end turn button.

Description: 'T' will be the hotkey for ending a turn

Message: "It took a bit of reading and testing around to figure out how to play. You guys could add some \"recommended actions\" or explain what 1 turn is. \n\nAlso, adding a \"end turn\" hotkey will enable a much smoother turn progression.`"

Story Points: 2 
Priority: medium
Risk: low

## Task Breakdown

- [x] Add input for T
- [x] Link T to ending turn
- [x] Add to controls menu
