### ISSUE TITLE
Three vs Three

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#144]
## User Story
As a user, I would like to control 3 characters and be against someone who also controls 3 characters.

Story Points: 5 
Priority: high
Risk: medium

## Task Breakdown

- [x] Add 3 more characters (1 hr)
- [x] Fix UI (2 hrs)
- [x] Fix current turn death bug (2 hrs)
- [x] remove Initiative (0.2hrs)
