### ISSUE TITLE
Obstructed Terrain

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#15]
## User Story
As a user, I want particular hexes on the map to be obstructed, such that they may not be moved through or attacked through.

Story Points: 5  
Priority: Medium 
Risk: Medium

## Task Breakdown

- [x] Implement a terrain obstruction (4 hrs)
- [x] Attach terrain obstructions to the playing field (3 hrs)
- [x] Implement other characters obstructing character movement (2 hrs)
- [x] Unit test behavior of terrain obstructions with regards to movement and attacks. (4 hrs)
