### ISSUE TITLE
Stage 1 - Welcome Message

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#151]
## User Story
As a user, I would like to know the purpose of the game

Story Points: 8 
Priority: high 
Risk: high

## Task Breakdown

- [x] Create a new scene for stage 1 welcome and link it to the menu
- [x] Make that scene link to the rest of the tutorial and complete and unlock the next tutorial
- [x] Add tile information
- [x] Add stats information
