### ISSUE TITLE
Stage 2 - Movement

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#152]
## User Story
As a user, I would like to know how to move my character.

Description: Load scene, introduce tutorial, red arrow on RocketCat, red arrow on stat panel, describe movement, red arrow pointing to target tile, press F and hover over tile, left click on tile, red arrow on move stat. End stage.

Story Points: 8 
Priority: High
Risk: Medium

## Task Breakdown

- [x] Make the scene (2 hrs)
- [x] Make the unique Start() function for this particular stage in the TutorialGameManager.cs (4 hrs)
- [x] Make the Stage2Controller.cs to handle the events in the scene, change the tutorial tooltips accordingly and the StageCompleted method and verifications (4 hrs)
