### ISSUE TITLE
Stage 3 - Attack

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#154]
## User Story
As a user, I would like to know how to use adjacent, AOE, line-target attacks.

Story Points: 8
Priority:  high  
Risk: medium

Description: RocketCat next to DC (Default Character), red arrow on ability panel, show Q ability info, prompt user to press Q and click on DC who is being shown with a red arrow. Show cooldown and explain. Hover over DC, explain target panel, show health value. End stage. (Adjacent)

Same thing with RocketCat W and also damaging an ally. (AOE)

Then go to Pengwin and show his W. (Line-target)

## Task Breakdown

- [x] Make new game manager (6 hrs)
- [x] Repair null pointers (3 hrs)
- [x] Make red arrow (2 hrs)
- [x] Make tutorial guide (3 hrs)
- [x] Make tutorial events that get fired correctly (3 hrs)
