### ISSUE TITLE
Update UI of Character Portraits

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#155]
## User Story
As a user, I would like each side of the match scene to contain a panel and icons of a player's character with a distinct border around the active character at all times.

Story Points: 8
Priority: high
Risk: high

## Task Breakdown

- [x] Introduce Players and States (2 hrs) @ModestosV 
- [x] Remodel Panels to contain 2 separate teams (4 hrs) @ModestosV 
- [x] Portrait of Active Character should be distinct and clear (3 hrs) @Arkondoma
