### ISSUE TITLE
Enhance Website Look and Feel

### ISSUE THREAD

**Issue by todd829** [ModestosV/BlackDice#157]
## User Story
As a user, I want a nicer website that looks like a Game's website with actual picture of the game, a working Navbar and a Footer.

Story Points: 3 (Could change depending on the effort)
Priority: LOW
Risk: LOW

## Task Breakdown

- [ ] Home page polishing with pictures of the game (? hrs)
- [ ] Navbar that doesn't just say 'Navbar' (? hrs)
- [ ] Footer that doesn't just say 'Footer' (? hrs)
