### ISSUE TITLE
Log Statements to Help Bug Fixing and Feature Suggestions

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#158]
## User Story
As a user, I would like the developers to know what is going on with my Unity scene when I submit bugs or suggestions.

Story Points: 5  
Priority: high  
Risk: medium

## Task Breakdown

- [x] Log events (0.5 hrs)
- [x] Check execution order of importnt UI elements' initializations (2 hrs)
- [x] Log clicks on tiles and abilities (1 hr)
- [x] Log other meaningful data (2 hrs)
- [x] Abstract code to make logging easier (1.5 hr)
- [x] Verify logging is usable via our logging service (1 hr)
