### ISSUE TITLE
Heal Ability

### ISSUE THREAD

**Issue by todd829** [ModestosV/BlackDice#17]
#17 

## User Story
As a user, I want to have a hero ability that heals a target allied character.

Story Points: 3 
Priority: Medium
Risk: Medium

## Task Breakdown

- [x] Create Ability of AbilityType HEAL and assign to Characters. (0.5 hrs)
- [x] Implement current health / max health in characters and prevent healing over max health. (2 hrs)
- [x] Create heal selection controller to handle inputs when heal ability is selected. (2 hrs)
- [x] Restrict heal abilities to ally targets and attack abilities to enemy targets (0.5 hrs)
