### ISSUE TITLE
Passive Button Clear Indicator

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#170]
## User Story
As a user, I would like to see a clear difference between active and passive buttons.

Story Points: 2
Priority: medium  
Risk: low

## Task Breakdown

- [x] Create new sprites for abilities (6 hrs)
- [x] Create new ability button prefabs (3hrs)
- [x] Modify scripts use new sprites for active and passive abilities (1hr)
