### ISSUE TITLE
Status Effect Silence

### ISSUE THREAD

**Issue by lambhunter0** [ModestosV/BlackDice#171]
## User Story
As a user, I would like to use abilities that silence a character (silenced target cannot use an ability on their next turn).

Story Points: 5
Priority: high
Risk: medium

## Task Breakdown

- [x] Add logic for silence mechanic (1 hrs)
- [x] Test ability that implements it (2 hrs)
- [x] UI for stun (2 hrs)
