### ISSUE TITLE
TA

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#177]
## User Story
As a user, I would like to have the TA character on my team.

Story Points: 8 
Priority: high
Risk: medium

Description:
Q: 4 tile range, increase speed
W: line attack that stuns (refactor)
E: Randomly buff ally with permanent DLL
R: Shield on each ally for 1 instance of damage (VERY HIGH COOLDOWN)

## Task Breakdown
- [x] Create TA Eagle Script (0.5 hr)
- [x] Q ability - "Swoop down" (1 hr)
- [ ] W ability - "refactor" - keep placeholder for now (need story to implement STUN)
- [x] E Ability - "Import DLLs" (1 hr)
- [x] R Ability - "Code Review" (1hr)
- [x] Sprites and Audio (2 hrs)
- [x] Acceptance Tests (1hr)
- [x] Unit Tests (2 hrs)
