### ISSUE TITLE
In-Game Character Selection Stage

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#178]
## User Story
As a user, I would like a game flow in line with chess, where players take turns moving (and using abilities) and where each player can choose which character to make active, rather than have turns based on character initiative.

Story Points: 8
Priority: high
Risk: high

## Task Breakdown

- [x] Planning (7 hrs)
- [x] CharacterState Logic (5 hrs)
- [x] TurnController Refactor (6 hrs)
- [x] Unit Tests (1 hr)
