### ISSUE TITLE
Stats Displayed in Target Panel

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#179]
## User Story
As a user, I would like to see the stats of a character displayed in the target panel when hovered over their portrait.

Story Points: 8
Priority: high
Risk: high

## Task Breakdown

- [x] Add mouseover property to Character Portraits (1 hr)
- [x] Update Portrait size [Technical Feature] (0.5 hrs)
- [x] Reimplement shield indicator to allow for more space on portraits (1 hr)
