### ISSUE TITLE
Visual Feedback for Character Selection Stage

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#191]
## User Story
As a user, I would like to know which of my characters are playable during my turn

Story Points: 8  
Priority: high  
Risk: high

## Task Breakdown

- [x] Add overlay that shows when characters are exhausted (2.5 hrs)
- [x] Add indicator that shows when character is selectable (1.5 hrs)
- [x] Consolidate active character circle into new indicator (1 hr)
- [x] Add turn text to show which player's turn it is (1 hr)
- [x] Restructure event system for new character indicators (1 hr)
