### ISSUE TITLE
Stage 4 - Heals

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#196]
## User Story
As a user, I would like instructions on how to heal allies.

Story Points: 5  
Priority: high
Risk: medium

Description: Place ally RocketCat that is damaged and Default Character. Default character moves to RocketCat and heals. Also show DC healing himself.

## Task Breakdown

- [x] Make the scene (2 hrs)
- [x] Make the unique Start() function for this particular stage in the TutorialGameManager.cs (4 hrs)
- [x] Make the Stage4Controller.cs to handle the events in the scene, change the tutorial tooltips accordingly and the StageCompleted method and verifications (4 hrs)
