### ISSUE TITLE
Stage 5 - Buffs

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#197]
## User Story
As a user, I would like instructions on how to use self buffs, aoe buffs, and how they can occur even when a character is not active. 

Story Points: 8 
Priority: high
Risk: medium

Description: Control RocketCat, use Q on Pengwin to show self-buff. Control Pengwin, move him next to ally character and use E on himself and ally to show AOE defensive buffs. Skip turns until it is Pengwin again. Use ult on RocketCat (make sure RocketCat has enough hp to live). Go to RocketCat and show that RocketCat now has 4 stacks. (Initial stack + 3 from auto attacking during Pengwin ult)

## Task Breakdown

- [x] Make the scene (2 hrs)
- [x] Make the unique Start() function for this particular stage in the TutorialGameManager.cs (4 hrs)
- [x] Make the Stage5Controller.cs to handle the events in the scene, change the tutorial tooltips accordingly and the StageCompleted method and verifications (4 hrs)
