### ISSUE TITLE
Move Character

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#2]
## User Story
As a user, I want to move a character on the playing field to any reachable, unoccupied tile by selecting the character and then clicking on the target tile.

Story Points: 8
Priority: High
Risk: Medium

## Task Breakdown
- [x] Create SelectionController script for selecting tiles and characters with the mouse. (5 hrs)
- [x] Create and implement ISelectionController interfaces for HexTile and Grid for applying selection effects to Unity game objects. (5 hrs)
- [x] Create and implement IMovementController interface for moving a character to a tile. (1.5 hrs)
- [x] Create and implement IGridTraversalController with search algorithm for finding shortest path between tiles. (7 hrs)
- [x] Setup Unity scene with grid and characters. (2 hrs)
- [x] Write unit tests for Selection, Movement and TraversalControllers. (4 hrs)
- [x] Unit testing second pass (7 hrs)
