### ISSUE TITLE
Overhaul Selection (Cancel Actions with Right Mouse Button)

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#208]
## User Story
As a user, when I select a character to make them active, default selection is FREE. Selecting an active character puts them into a MOVEMENT state. Right click puts active character into a FREE state, cancelling any movement or abilities.

Story Points: 5  
Priority: high
Risk: high

## Task Breakdown

- [x]  Left click active character to put them in movement state (.5 hrs)
- [x] Right click to cancel any action (.25 hrs)
- [x] Escape to open menu (.25 hrs)
- [x] Update Controls Page and Main Menu Behavior (1.5 hrs)
