### ISSUE TITLE
Show Current / Base Stats

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#229]
## User Story
As a user, I would like to see character stats at their current value in comparison to their base value.

Example: Buffing Pengwin Defense by 20 shows 120 / 100.

Story Points:3  
Priority: medium 
Risk: medium

## Task Breakdown

- [x] Check is current is higher than original value
- [x] Display current over original
- [x] Create new value to return that is unchanged after receiving stat values
