### ISSUE TITLE
Start Match

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#23]
## User Story
As a user, I want to start a local match, whereupon two characters belonging to two players are loaded on the playing field.

Story Points: 3
Priority: High
Risk: Medium

## Task Breakdown
- [x] Create a basic scene with a playing field and two characters. (2 hrs)
- [x] Load scene when start match button on Main Menu is pressed. (1 hr)
- [x] Distinguish characters between the two players with a UI panel that shows the selected characters owner player number. (2 hrs)
- [x] Write unit tests for the selection controller covering the player panel. (2 hrs)
