### ISSUE TITLE
Stage 1 - HUD Elements

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#230]
## User Story
As a user, I would like the first stage of the tutorial to be consistent with stage 2/3.

Story Points: 8
Priority: high  
Risk: medium

## Task Breakdown

- [x] Fix Camera Angle
- [x] Fix Health Bar placement
- [x] Clean up UI clutter
- [x] Set info as Hideable
