### ISSUE TITLE
In Game Movement and Animation

### ISSUE THREAD

**Issue by RyanL94** [ModestosV/BlackDice#234]
This was not going to be included because the movement happens already and this would just add visible finesse that doesn't add overall to the development of the project.

## User Story
As a user, I would like my characters to move along the path with an animation.

Story Points: 8  
Priority: High  
Risk: Medium

## Task Breakdown

- [x] Obtain Assets for each character
- [x] Create Animators for each character asset
- [x] Rename brought in assets and add them to folders to be easy to find
- [x] Create a method to follow returned path
- [x] Add a method to look in the direction of movement
- [x] Replace default character models with new ones
- [x] Resize models and add on scripts, alter children to reflect size and asset change
