### ISSUE TITLE
Reduce size of map by 2 tiles all around

### ISSUE THREAD

**Issue by todd829** [ModestosV/BlackDice#239]
## User Story
As a user, I would like to have a smaller map for quicker game

Story Points: 3
Priority: medium
Risk: low

## Task Breakdown

- [ ] Reduce size of map Hexapark (3 hrs)
- [ ] Reduce size of map tutorial 2 (1 hrs)
- [ ] Reduce size of map tutorial 3 (1 hrs)
- [ ] Reduce size of map tutorial 4 (1 hrs)
