### ISSUE TITLE
End Match

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#24]
## User Story
As a user, I want a match to end, either through surrender or by win condition when all the enemies characters are dead.

Story Points: 5  
Priority: High
Risk: Medium

## Task Breakdown
- [x] Implement surrender option to end match and return to main menu (2.5 hrs)
- [x] Implement character death (1 hr)
- [x] Implement win condition triggering the end of match and return to main menu (2.5 hrs)
- [x] Write unit tests for new functionality. (1.5 hrs)
