### ISSUE TITLE
Wednesday Demo Tasks

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#241]
## Task Breakdown

- [x] Sheep: Movement, Ultimate, Headbutt #246 @lambhunter0
- [x] Professor Owl #111 @lambhunter0 
- [x] Movements and Animations #234 @RyanL94
- [x] Tutorial 3  #154 @marcdragon123 
- [x] Tutorial 4 #245 @todd829 
- [x] Rename Game #147 @ModestosV 
- [x] Portrait stuff #179 #195 @Arkondoma
- [x] HealthBar updating correctly @Arkondoma 
- [x] Grass tiles consistency @todd829 
- [ ] Sheep Heal AOE clickable enemy @lambhunter0

- [x] New download link @RyanL94 @marcdragon123
