### ISSUE TITLE
Match History

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#25]
## User Story
As a user, I want to be able to view the result history of matches I have played.

Story Points: ?  
Priority: ?  
Risk: ?

## Task Breakdown
- [ ] Implement persistent storage for match history data. (8 hrs)
- [ ] Add match results to persistent storage. (2 hrs)
- [ ] Create scene for viewing match history and link to main menu. (4 hrs)
