### ISSUE TITLE
Player Statistics

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#26]
## User Story
As a user, I want to be able to view detailed player statistics (e.g. total deaths, characters killed, damage dealt, distance traveled, Easter eggs found).

Story Points: ?  
Priority: ?  
Risk: ?

## Task Breakdown
- [ ] Implement persistent storage for player statistics data. (8 hrs)
- [ ] Add statistics incurred during matches to persistent storage. (2 hrs)
- [ ] Create scene for viewing player statistics and link to main menu. (4 hrs)
