### ISSUE TITLE
Logitech Controller Support

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#272]
All controller stories were not part of our release plan for two reasons. First, we did not know how valuable this would be until we demoed the game during our poster presentation. Second, no team member had experience with adding peripherals outside of keyboard/mouse.

## User Story
As a user, I would like to play with a Logitech Controller.

Story Points: 5
Priority: medium  
Risk: medium

## Task Breakdown

- [ ] Research Controller Support in Unity (3 hrs)
- [ ] Add Support for Q, W, E, R, T, F, Left Click, Right Click Buttons (1 hr)
- [ ] Add Support for cursor movements (2 hrs)
- [ ] Manually test controller (1 hr)
