### ISSUE TITLE
Cross Platform Builds

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#31]
## User Story
As a user, I would like to ensure that updates to my game are stable, whether I am on a Mac or Windows computer.

Story points: 8
Risk: High
Priority: High

## Task Breakdown

- [x] Research Travis, Unity, .NET setups (30 hrs)
- [x] Automate Cloud Builds and Unit Tests on master using Unity Cloud Build (3 hrs)
- [x] Update Wiki with relevant info (.25 hrs)
