### ISSUE TITLE
Constrained Movement

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#33]
## User Story
As a player, I want the movement of my character on my turn to be constrained to the number of tiles equal to my speed attribute.

Story Points: 3 
Priority: Medium 
Risk: Medium

## Task Breakdown

- [x] Constrain the distance of character movement to the moves remaining for that character. (0.5 hrs)
- [x] Implement a movement selection state that error highlights path tiles when a move is beyond the characters range. (0.5 hrs)
- [x] Implement current value for CharacterStats and StatDisplays to display both values. (2 hrs)
- [x] Write unit tests for the new functionality. (0.5 hrs)
