### ISSUE TITLE
Create Game Prototype

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#38]
## Epic
As a user, I want to be able to play a prototype of the application, in order to gauge my potential interest and give feedback before decisions are finalized.

## User Stories
- [x] #1 View Hex Grid
- [x] #2 Move Character
- [x] #4 View Character
- [x] #5 Main Menu
- [x] #6 View Character Info
- [x] #23 Start Match
- [x] #10 Attack Ability
- [x] #11 Turn Based Combat
- [x] #24 End Match
