### ISSUE TITLE
Turn Visibility

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#39]
## User Story
As a player, I want to have a visual indicators as to which character is currently active, and the order character turns that will follow it.

Story Points: 5 
Priority: Medium 
Risk: Medium

## Task Breakdown

- [x] Create UI and/or tile highlighting solution for indicating the active character (3.5 hrs)
- [x] Create UI solution for indicating active character sequence in round (2 hrs)
- [x] Create unit tests for turn tracker functionality (1 hr)
