### ISSUE TITLE
Access Account Remotely

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#42]
## User Story
As a user, I want to be able to access my game account from a different computer.

Story Points: 13
Priority: High
Risk: High

## Task Breakdown

- [x] Create DTOs for objects that we will pass in our requests/replies (1 hr)
- [x] Transform the communication to post to information (3 hrs)
- [x] Address comments of #43 (5 hrs)
- [x] Transform Network to Class (4 hrs)
     - [x] Decide to use Async-wait or using & yield
     - [x] Make specific router to post to specific routes 
     - [x] Decide to use properties in the class
- [x] Deploy web app to server hosted on the web (1 hr)
     - [x] Deploy containerized database to web server (1 hr)
     - [x] Containerize MongoDB database (1 hr)
     - [x] Setup PM2 and pull the repo and make symlinks (3 hr) (includes funky devops stuff)
- [x] Point game client web requests to web server endpoint (1 hr)
- [x] Style Code (4 hrs)
     - [x] Refactor server-side code
     - [x] Use JSON library to make requests + handle replies
     - [x] Refactor client-side implementation to improve abstractions
