### ISSUE TITLE
Submit Feedback

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#56]
## User Story
As a user, I would like to submit feedback to developers.

Story Points: 8
Priority: high  
Risk: low

## Task Breakdown

- [x] Add Event Handling to Existing Code [Technical]
- [x] Add UI for Submitting Feedback
- [x] Add Server-Side Handling of Feedback
