### ISSUE TITLE
View Character Info

### ISSUE THREAD

**Issue by Arkondoma** [ModestosV/BlackDice#6]
## User Story
As a user, I want a character's attribute information to be displayed on the UI when the character is selected.

Story Points: 5  
Priority: High  
Risk: Medium

## Task Breakdown
- [x] Create and implement basic character SelectionController (1 hr)
- [x] Create and implement CharacterStat and StatModifier classes (3 hrs)
- [x] Create Character script and setup Unity scene with multiple characters (1.5 hrs)
- [x] Create and implement StatPanel and StatDisplay scripts for displaying a selected characters stats in the UI (3 hrs)
- [x] Add UI elements to scene. (1.5 hrs)
- [x] Write unit tests for character stat system (4 hrs)
- [x] Write unit tests for StatPanelController and StatDisplayController and unit testing second pass (4 hrs)
