### ISSUE TITLE
Sprint 5 - Week 1 Refactor

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#68]
Refactoring never ends, so we will be imposing a hard deadline of November 14, 2018, to clean up any code left over from Release 1.

## Task Breakdown

- [x] Implement HttpClient over coroutines
- [x] Refactor selection controllers to use template method pattern.
- [x] Create abstract CharacterController, and concrete DefaultCharacterController a with fixed stat and ability set.
- [x] Map character stats and ability values to strings.
- [x] Move ability execution logic to ability from character.
- [x] Add Abstract classes in cases where code duplication can be avoided (Panel, Ability Controller)
- [x] Renaming classes
- [x] classifying all server components
- [x] test new implementation
