### ISSUE TITLE
Character Stats

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#7]
## User Story
As a user, I want a character to have attributes that represent their durability, mobility and effectiveness in combat.

Story Points: ?  
Priority: ?  
Risk: ?

## Task Breakdown

- [ ] Implement underlying character stat system (4 hrs)
- [ ] Write unit testing for character stat system (4 hrs)
- [ ] Incorporate character stats into a character (4 hrs)
