### ISSUE TITLE
Rocket Cat, Ability 1: Scratch

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#70]
## User Story
As a player using the Rocket Character hero, I want my first ability to be "Scratch". Scratch is a melee range basic attack that does a fixed amount of damage and does not have an additional turn cooldown.

Story Points: 3  
Priority: Medium  
Risk: Medium

## Task Breakdown

- [x] Create ability with range 1, fixed damage. (2 hrs)
- [x] Implement range limiting logic for abilities. (2 hrs)
- [x] Add ability animation for scratch. (2 hrs)
- [x] Add ability sound for scratch. (2 hrs)
- [x] Implement ability cooldowns. (2 hrs)
