### ISSUE TITLE
Basic In-Game Visual Feedback

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#74]
## User Story
As a user, I would like to have visual cues on actions that are being performed in-game.

Story Points: ?  
Priority: high 
Risk: ?

## Task Breakdown

- [ ] Highlight attackable enemies #84
- [x] Health bars on each character #75 
- [x] Highlight active character #85
- [ ] Have visual feedback on which characters you control vs enemy characters #86
- [ ] Show a death icon when hovering over a character with an ability that will deals lethal damage #88
- [x] Show cooldowns #79
