### ISSUE TITLE
Health Bars

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#75]
## User Story
As a player, I want health to see a health bar over characters in a match. This health bar should show the relative value of current health to max health based on the color and/or size of parts of the bar. The bar may also include text at all times or on mouse-over showing the numerical values for that characters health stats.

Story Points: 5 
Priority: Medium
Risk: Medium

## Task Breakdown

- [x] Create health bar UI view object in the Unity scene. [2 hrs]
- [x] Link the character's health stat with the HealthBar such that it updates accordingly when the character's health stat changes. [3 hrs]
- [x] Write unit tests for applicable new components. [1.5 hrs]
