### ISSUE TITLE
Add Terms Of Service

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#78]
## User Story
As a user, I would like to know what my rights are, when installing the application.

Story Points: 2  
Priority: high  
Risk: low

## Task Breakdown

- [x] Add terms of service
- [x] Block download until user has accepted ToS
- [x] Create new installer for the game
- [x] Update site with new installer and remove sidebar
