### ISSUE TITLE
Show Ability Cooldowns

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#79]
## User Story
As a user, I would like to see how much time is needed to reuse an ability.

Story Points: 3  
Priority: medium  
Risk: low

## Task Breakdown

- [x] Display blue ability button and show # of turns remaining (8 hrs)
- [x] Refactor Ability Panel and add a controller (6 hrs)
- [x] Refactor game manager to have the new controller and panel (2 hrs)
- [x] Create Unit tests for the new controller (2 hrs)
- [x] Fix bugs and issues with rendering (2 hrs)
