### ISSUE TITLE
Rocket Cat, Ability 3: Catscratch Fever

### ISSUE THREAD

**Issue by 0matleb2** [ModestosV/BlackDice#83]
## User Story
As a player using the Rocket Character hero, I want my third ability to be a passive ability that causes consecutive scratches to deal increasing damage and increase character speed.

Story Points: 5  
Priority: Med 
Risk: Med

## Task Breakdown

- [x] Implement Effects (5 hrs)
- [x] Create Catscratch Fever passive ability (2 hrs)
- [x]  Write Unit Tests for This ability (2 hrs)
