### ISSUE TITLE
Pengwin - Ability 1 - Penguin Slap

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/BlackDice#99]
## User Story
As a user playing Pengwin, I would like to use my first ability.

Story Points: 5  
Priority: medium
Risk: low

Part of #72 

## Task Breakdown

- [x] create pengwin (1 hrs)
- [x] create slap (0.5 hrs)
- [x] fix UI, sounds, and animations (1 hrs)
- [x] unit tests (0.5 hrs)
